### ISSUE TITLE
Discovering firetv communication port

### ISSUE THREAD

**Issue by tmm1** [Sor3nt/Amazon-Fire-TV-Stream#1]
Hi, thanks for writing this library!

I noticed the port is hard coded, and wanted to suggest how to find the correct port. The FireTV advertises a bonjour service named `_amzn-wplay._tcp`. Using any bonjour browser app or library will show this service and the correct port.

For example, on macOS you can run:

```
$ dns-sd -B _amzn-wplay._tcp local
Browsing for _amzn-wplay._tcp.local
DATE: ---Tue 06 Jun 2017---
10:01:38.843  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
10:01:38.843  Add        2   4 local.               _amzn-wplay._tcp.    amzn.dmgr:649079E36FF650C95604A3397843E704:QZT4YaSve2:325301

$ dns-sd -L "amzn.dmgr:649079E36FF650C95604A3397843E704:QZT4YaSve2:325301" _amzn-wplay
Lookup amzn.dmgr:649079E36FF650C95604A3397843E704:QZT4YaSve2:325301._amzn-wplay._tcp.local
DATE: ---Tue 06 Jun 2017---
10:02:02.821  ...STARTING...
10:02:02.822  amzn\.dmgr:649079E36FF650C95604A3397843E704:QZT4YaSve2:325301._amzn-wplay._tcp.local. can be reached at 10-0-1-108.local.:53725 (interface 4)
 s=0 at=JG69s/Dch8Tp n=Aman\'s\ Fire\ TV\ stick tr=tcp sp=54118 pv=1 mv=2 v=2 a=0 u=649079E36FF650C95604A3397843E704 ad=A2LWARUGJLBYEW dpv=1 t=8 f=0
```

and see that "Aman's Fire TV stick" is available on 10.0.1.108:53725

>can be reached at 10-0-1-108.local.:53725

**Comment by Sor3nt** [comment]
Oh awesome, thanks for sharing this, i will add this into the source :)

**Comment by Sor3nt** [comment]
thanks again, i managed to write a small mDNS service to lookup the amazon devices. code updated.
